import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bakes by Lee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      {/* Tidio Chat Script */}
        <script
          src="//code.tidio.co/ozscrti2k8tjb2iajcxea3vn5tthajbu.js"
          async
        ></script>
      </head>
      <body className={inter.className}>
      {children}
      </body>
    </html>
  );
}
